name: Push Tests
on: [push]
jobs:
  Run-Linting-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Prettier formatting check
        run: npx prettier . --check
